version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: jobtracker-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: jobtracker
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jobtracker-network

volumes:
  postgres-data:

networks:
  jobtracker-network:
    driver: bridge 